---
- name: Copy files to remote server
  synchronize:
    src: ./../files
    dest: /srv/app
    recursive: yes
  become: yes

- name: Run docker-compose up -d
  command: docker-compose up -d
  args:
    chdir: /srv/app/files