---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install packages required for apt to work over HTTPS
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ubuntu_version }} stable"
    state: present
  vars:
    ubuntu_version: "ubuntu jammy"

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Install Docker Compose
  shell: curl -sL "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/do
  args:
    warn: false
  vars:
    docker_compose_version: "1.29.2"

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes