version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: ./php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Kfhj%hTavJ@4a
      MYSQL_DATABASE: testbase
      MYSQL_USER: testuser
      MYSQL_PASSWORD: Pcanh~tugy4e7
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge